name: cd

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Version Bump
        uses: phips28/gh-action-bump-version@master
        with:
          skip-tag: true
          minor-wording: add:,minor,feat

      - name: Build Changelog message
        id: changelog
        uses: scottbrenner/generate-changelog-action@master
        env:
          REPO: ${{ github.repository }}

      - name: Read new Version
        id: reader
        run: |
          PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
          echo "::set-output name=read_version::$PACKAGE_VERSION"

      - name: Create Github Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.reader.outputs.read_version }}
          release_name: Release ${{ steps.reader.outputs.read_version }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: "https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/health"
